apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tapathon-machine-setup
spec:
  title: TAPathon Machine Setup
  description: Guides a TAPathon participant through steps required to setup their machine
  vendor: tanzu.vmware.com
  difficulty: beginner
  duration: 1h
  content:
    files: github.com/p-ssanders/tapathon-workshops/machine-setup?ref=main
  session:
    namespaces:
      budget: small
      role: view
    applications:
      terminal:
        enabled: false
    env:
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
    ingresses:
    - name: nginx-via-proxy
      protocol: http
      host: nginx.$(session_namespace).svc.cluster.local
      port: 8080