# This should probably live somewhere else
apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: tapathon
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
  workshops:
  - name: tapathon-machine-setup
    reserved: 0
    capacity: 10
    expires: 1h
    orphaned: 10m